### ISSUE TITLE
No configuration to disable telemetry

### ISSUE THREAD

**Issue by slaughtr** [hashicorp/vscode-hcl#169]
Hello! 

As someone who is privacy and security minded, I would really love if there was a configuration to disable telemetry. This is in line with how most VS Code extensions handle telemetry, and would definitely make me and my coworkers and the entirety of my security organization very happy.

Not to be negative, but I was pretty flummoxed to find out that this extension had been taken over and telemetry added in a completely silent and opaque way. I understand the need to take over the namespace of the extension when Hashicorp adopted it, but I don't recall ever seeing any notification about the change or any telemetry being added.

**Comment by jpogran** [comment]
Hi @slaughtr, we're really sorry about this and we can see how this can impact your experience using our tools.

The good news is you've **always** been able to disable telemetry in vscode-hcl, as well as any of HashiCorp's other extensions that collect telemetry. To do this right now, follow [VS Code's documentation](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting) and set `telemetry.telemetryLevel` to `all`, `error`, `crash`, or `off`.

For example:

```
"telemetry.telemetryLevel": "off"
```

This will disable telemetry for VS Code and *all* extensions that use Microsoft's [@vscode/extension-telemetry module](https://www.npmjs.com/package/@vscode/extension-telemetry), which we use in vscode-hcl and in vscode-terraform.

You can see exactly what we log (along with any other extension) by [viewing VS Code's Telemetry output channel](https://code.visualstudio.com/docs/getstarted/telemetry#_output-channel-for-telemetry-events). That article explains how to view the events, along with a section on how both VS Code and extensions like ours adhere to GDPR. We do not collect any PII. The data we do collect help us make better informed product decisions which the wider user base can then benefit from, e.g. if a high % of users open Nomad files it is a signal for us that it's worth investing into a dedicated Nomad extension.

We'll be adding a telemetry section to the vscode-hcl README similar to the existing one in [vscode-terraform](https://github.com/hashicorp/vscode-terraform#telemetry) so that people know in the future.

We apologize that HashiCorp taking over this extension caught you by surprise. As a team we strive to interrupt our users as little as possible with popups and messages, so do not include 'What's new' type events when extensions are updated. We did a [blog post](https://www.hashicorp.com/blog/announcing-the-hcl-extension-for-visual-studio-code-0-1) announcing the transition, but agree we could have done more to communicate this.

**Comment by slaughtr** [comment]
Well today I learned for sure! I was not aware of that module or that the base `telemetry` property would apply in (some? most?) cases. Very cool!

I really appreciate the thorough response, and look forward to what you have in store for the future for the extension :)
