### ISSUE TITLE
New icon is too big

### ISSUE THREAD

**Issue by nkkowa** [hashicorp/vscode-hcl#172]
The new icon is a bit big and doesn't line up well with other icons. Perhaps standardize with the spacing from the [Terraform extension](https://github.com/hashicorp/vscode-terraform/blob/main/assets/icons/terraform.svg).

![image](https://user-images.githubusercontent.com/83962080/203106321-68f022ff-bd16-43b5-9ee2-3d4938c1ccf7.png)

**Comment by radeksimko** [comment]
Hi @nkkowa 
Unfortunately this is a side effect of what I'd consider a bug in VS Code, where extension-contributed icons are treated differently from the builtin ones. I originally raised this in https://github.com/microsoft/vscode/issues/154492 but it seems that VS Code folks aren't too keen to address that.

[The Terraform icon specifically actually is built into `seti-ui`](https://github.com/jesseweed/seti-ui/blob/master/icons/terraform.svg) (library used by VS Code to render icons which otherwise aren't provided by extensions), whereas the HCL icon is provided by the HCL extension.

I tried to play with various different paddings and margins in the SVG, but I wasn't able to align it in any way. I think the best course of action would therefore be contributing the HCL icon into `seti-ui`, so they both use the same styling rules.

**Comment by radeksimko** [comment]
btw. We could _also_ contribute Packer icon to seti, which was the context of the original PR as submitted by @bmalehorn 
https://github.com/hashicorp/vscode-hcl/pull/151
