### ISSUE TITLE
Allow using "#" for line comments

### ISSUE THREAD

**Issue by khaliddermoumi** [hashicorp/vscode-hcl#313]
Please support using "#" as the line comment character.

So far, the extension uses only "//", and there seems to be no way to configure this. 
As "#" is the typical line comment character in Terraform, when using this extension with TF, it would be very desirable to have "#" in the hcl files too.

**Comment by jpogran** [comment]
Hi @khaliddermoumi, this extension is not meant to be used for Terraform (.tf) files, as described in the [README](https://github.com/hashicorp/vscode-hcl?tab=readme-ov-file#usage). This extension uses the official HCL library rules as defined here: [hclsyntax/spec.md](https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#comments-and-whitespace) which state no preference for which to use. There is no way to configure this, because VS Code itself does not provide a way for a user to do this.

The official [HashiCorp Terraform Extension](https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform) uses `#` as the [line comment symbol](https://github.com/hashicorp/vscode-terraform/blob/38c3b92132eb3fec1fc4edb936ee923f08499f06/language-configuration.json#L3). We strongly recommend you use vscode-terraform to edit Terraform files. May I ask why you are using the HCL extension for Terraform files?

**Comment by khaliddermoumi** [comment]
Hi @jpogran!

I am using the extension to edit terragrunt files (.hcl), which are authored in terraform syntax. You can't use the dedicated TF extension for this, as it would validate the terragrunt specific parts as "errors". vscode-hcl is the better choice, but TF should use the "#" comment symbol (just like the TF extension).

I am sure this is a common issue, as terragrunt is widely used by TF users.

**Comment by suburbanworrier** [comment]
Hi

Burnt way too long trying to sort out what extensions are required on a my new laptop to work on a Terragrunt project. I thought I'd got it sorted when I installed this one but the double slash comments are driving me insane as all of the code I'm working with is chock full of `# comments`.

@jpogran says:
> the official HCL library rules ... state no preference for which to use

and 
> The official [HashiCorp Terraform Extension](https://marketplace.visualstudio.com/items?itemName=hashicorp.terraform) uses #

so who decided this one must use `//`?

Please, please make it configurable or just change to the more widely used `#`.
